### ISSUE TITLE
论文下载

### ISSUE THREAD

**Issue by milktang** [MLjungg/CTGAN_M-Thesis#1]
"Synthetic Data Generation for the Financial Industry Using Generative Adversarial Networks"
请问这篇论文在哪可以下载到？方便提供论文吗？

**Comment by milktang** [comment]
Where can I download this paper? Is it convenient to provide papers

**Comment by MLjungg** [comment]
Hi, 

You can find the paper here:

https://www.diva-portal.org/smash/get/diva2:1591892/FULLTEXT01.pdf
